<a href="https://colab.research.google.com/github/ANKIT-KANDULNA/CS318_DL-LAB/blob/main/Experiment-1/DL_lab_exp1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Why Tensors are better than Lists?

In [28]:
import time
N = 1000000

list1 = list(range(N))
list2 = list(range(N))

tensor1 = torch.arange(N)
tensor2 = torch.arange(N)

start = time.time()
list_result = [list1[i] * list2[i] for i in range(N)]
end = time.time()

print("List multiplication time:", end - start, "seconds")

start = time.time()
tensor_result = tensor1 * tensor2
end = time.time()

print("Tensor multiplication time:", end - start, "seconds")

List multiplication time: 0.12317180633544922 seconds
Tensor multiplication time: 0.007215738296508789 seconds


Create 1 D,2D and 3D tensors using Pytorch and Numpy.

In [2]:
import numpy as np

a1 = np.array([1, 2, 3])

a2 = np.array([[1, 2, 3], [4, 5, 6]])

a3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])


Torch

In [7]:
import torch

t1 = torch.tensor([1, 2, 3])

t2 = torch.tensor([[1, 2, 3], [4, 5, 6]])

t3 = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

Basic Operations on tensors

In [5]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x + y)
print(y - x)
print(x * y)
print(y / x)

[5 7 9]
[3 3 3]
[ 4 10 18]
[4.  2.5 2. ]


In [8]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

print(x + y)
print(y - x)
print(x * y)
print(y / x)

tensor([5, 7, 9])
tensor([3, 3, 3])
tensor([ 4, 10, 18])
tensor([4.0000, 2.5000, 2.0000])


Indexing and Slicing

In [9]:
a = np.array([[10, 20 ,30], [40, 50, 60]])

print(a[0:1])
print(a[:1])
print(a[1:])

[[10 20 30]]
[[10 20 30]]
[[40 50 60]]


In [10]:
a = torch.tensor([[10, 20 ,30], [40 ,50, 60]])

print(a[0:1])
print(a[:1])
print(a[1:])

tensor([[10, 20, 30]])
tensor([[10, 20, 30]])
tensor([[40, 50, 60]])


Boolean Masking

In [11]:
a = np.array([1, 2, 3, 4, 5])

mask = a > 3
print(a[mask])

[4 5]


In [12]:
t = torch.tensor([1, 2, 3, 4, 5])
print(t[t > 3])

tensor([4, 5])


Extracting Subtensor

In [13]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(a[0:2, 1:3])

[[2 3]
 [5 6]]


In [15]:
t = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(t[0:2, 1:3])

tensor([[2, 3],
        [5, 6]])


Shape Manipulation

In [18]:
a = np.array([1, 2, 3, 4, 5, 6])
a = np.reshape(a, (2, 3))
print(a)

[[1 2 3]
 [4 5 6]]


In [19]:
t = torch.tensor([1, 2, 3, 4, 5, 6])
t = t.reshape(2, 3)
print(t)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [20]:
t.view(2, 3)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [22]:
t = torch.tensor([1, 2, 3])
t = t.unsqueeze(0)
t = t.unsqueeze(1)
print(t)

tensor([[[1, 2, 3]]])


In [23]:
t = torch.squeeze(t)
print(t)

tensor([1, 2, 3])


Broadcasting

In [24]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])

print(a + b)

[[11 22 33]
 [14 25 36]]


In [25]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([10, 20, 30])

print(t1 + t2)

tensor([[11, 22, 33],
        [14, 25, 36]])


In place and Out of place operations

In [26]:
x = torch.tensor([1, 2, 3])
y = x + 1
print(y)

tensor([2, 3, 4])


In [27]:
print("Before IN Place Operation")
x = torch.tensor([1, 2, 3])
print(x)
print("After IN Place Operation")
x.add_(1)
print(x)

Before IN Place Operation
tensor([1, 2, 3])
After IN Place Operation
tensor([2, 3, 4])
